# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dockerhub1'
        repository: 'ddschmid/webapptest'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 

    - task: SSH@0
      inputs:
        sshEndpoint: 'srvdevlife_ssh'
        runOptions: 'commands'
        commands: |
          sudo /usr/local/bin/docker pull ddschmid/webapptest:latest
          sudo /usr/local/bin/docker stop ddschmid-webapptest
          sudo /usr/local/bin/docker rm ddschmid-webapptest
          sudo /usr/local/bin/docker run --name ddschmid-webapptest -d -p 32780:80 -e "ASPNETCORE_ENVIRONMENT=Development" ddschmid/webapptest:latest