# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dockerhub1'
        repository: 'ddschmid/webapptest'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 

    - task: SSH@0
      inputs:
        sshEndpoint: 'srvdevlife_ssh'
        runOptions: 'inline'
        inline: 'sudo docker images'